name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation
        uses: Ultimate-Anarchy-Team-COSC345/COSC345.2@v2
        with:
          inputs: "COSC345.2"
          module-name: MyLibrary
          output: "Documentation"
      - name: Upload Documentation to Wiki
        uses: Ultimate-Anarchy-Team-COSC345/COSC345.2@v2
        with:
          path: "Documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
