name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/documentation.yml
      - Ultimate-Anarchy-Team-COSC345/COSC345.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Generate Documentation
        uses: Ultimate-Anarchy-Team-COSC345/COSC345.2@master
        with:
          inputs: "Ultimate-Anarchy-Team-COSC345/COSC345.2"
          output: "Documentation"
      - name: Upload Documentation to Wiki
        uses: Ultimate-Anarchy-Team-COSC345/COSC345.2@master
        with:
          path: "Documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
